require('json2ify')
require('es5-shimify')
require('jqueryify')
require('lib/vendor/jquery.easing.1.3')
require('lib/vendor/jquery.tipTip')
require('lib/normalizeurl')

require('spine')
require('spine/lib/ajax')
require('spine/lib/manager')
require('spine/lib/route')
require('spine/lib/tmpl')
require('spine/lib/relation')
require('lib/spine.uploader')
